### ISSUE TITLE
Crash on SSP throwing dynamite

### ISSUE THREAD

**Issue by briansemrau** [RedstoneParadox/NiceToHave#1]
Version: 1.0.0
Log: https://paste.ee/p/8AKt5
To reproduce: Throw a stick of dynamite in single player

The crash log details an invalid cast from ClientWorld to ServerWorld happening somewhere in ThrownDynamiteEntity.onCollision()

**Comment by RedstoneParadox** [comment]
This should be fixed in v1.0.1 which I just released here on GitHub and should be approved on CurseForge shortly. Please let me know if this is not fixed; I could tell what caused the issue from your crash log but the issue itself didn't seem to show up in the dev environment so I'm not certain if it is fixed.
